const FarmData = [
  {id: 1,
  farmname: "Pedersen Farms",
  latitude: 42.8949,
  longitude:-77.0924,
  postalcode: 14547,
  acrage: "" ,
  soilhealthpractices: ["Soil Amendment", "Cover Crops"],
  remarks: "For more information, check: http://pedersenfarms.com/" ,
  },
  {id: 2,
  farmname: "Gary Swede Farm",
  latitude: 42.8325,
  longitude:-77.9967,
  postalcode: 14525,
  acrage: "",
  soilhealthpractices: ["Strip Till", "No Till", "Cover Crops", "Nutrient Management"],
  remarks: "",
  },
  {id: 3,
  farmname: "Branton Farms",
  latitude: 42.9813,
  longitude: -77.9510,
  postalcode: 14482 ,
  acrage: "",
  soilhealthpractices: ["Reduced Till", "No Till", "Strip Till", "Nutrient Management", "Drainage Management"],
  remarks:"",
  },
  {id: 4,
  farmname: "Angel Rose Dairy",
  latitude: 42.3029,
  longitude: -75.4578,
  postalcode:13733,
  acrage:"",
  soilhealthpractices: ["Cover Crops", "No Till"],
  remarks: "" ,
  },
  {id: 5,
  farmname: "Morning Star Farms",
  latitude: 43.7828,
  longitude:-76.0160,
  postalcode: 13605,
  acrage:"" ,
  soilhealthpractices: ["Cover Crops", "No Till"],
  remarks: "",
  }
]

export default FarmData;
